[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  # Free plan: 26s max for regular functions
  # Background functions: 15 minutes max (available on all plans)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

