[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Increase timeout for AI functions (default is 10s, max is 26s on Pro)
[functions."diagram-to-journey"]
  timeout = 26

[functions."transcript-to-journey"]
  timeout = 26

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

